config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :sites, only: [ :show ]

  resources :galleries, only: [] do
    resources :pics, only: [ :index ]
  end

  resources :pics, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
class Content  < ApplicationRecord
    belongs_to :page
    has_one_attached :source

    def to_partial_path = "contents/#{ type ? type.downcase : 'content'}"
end

app/models/gallery.rb
class Gallery < Page
    def pics
        # change the select to where (maybe?)
        contents.select { |content| content.position=="pic" }
    end
end

app/models/hero.rb
class Hero < Page
end

app/models/image.rb
class Image < Content
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :site

  has_many :contents, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :site_id }
  validates :anchor, uniqueness: { scope: :site_id }

  before_save :slugify, if: :will_save_change_to_name?

  def get_content(position)
   indexed_contents[position] || Content.new(body: "")
  end

  def to_partial_path = "pages/#{ type ? type.downcase : 'page'}"

  private

  def indexed_contents
    @idx_contents ||=  contents.index_by(&:position)
  end

  def slugify
    self.anchor = name.parameterize
  end
end

app/models/pic.rb
class Pic < Content
    # Pic might not be a content but belongs to a gallery
    # low fi thumb could be a content of type Image
    # Gallery would be in charge of managing the sync between them
    # how to manage the active storage relation

    has_one_attached :source do |attachable|
        attachable.variant :small, resize_to_limit: [ 25, 25 ], preprocessed: true
        attachable.variant :medium, resize_to_limit: [ 300, 300 ], preprocessed: true
        attachable.variant :big, resize_to_limit: [ 700, 700 ], preprocessed: true
    end
end

app/models/site.rb
class Site < ApplicationRecord
    has_many :pages, dependent: :destroy

    validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  include ActiveStorage::SetCurrent

  before_action :set_gallery, only: %i[ index ]

  # GET /galleries/:gallery_id/pics
  def index
    @pics = @gallery.pics
  end

  # GET /pics/:id
  def show
    @pic = Pic.find(params.expect(:id))
  end

  private

  def set_gallery
    @gallery = Gallery.includes(contents: { source_attachment: { blob: :variant_records } }).find(params.expect(:gallery_id))
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  include ActiveStorage::SetCurrent

  before_action :set_site, only: %i[ show edit update destroy ]

  # GET /sites or /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1 or /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites or /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: "Site was successfully created." }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1 or /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: "Site was successfully updated." }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1 or /sites/1.json
  def destroy
    @site.destroy!

    respond_to do |format|
      format.html { redirect_to sites_path, status: :see_other, notice: "Site was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.includes(pages: { contents: { source_attachment: { blob: :variant_records } } }).find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def site_params
      params.expect(site: [ :title ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/contents/_content.html.erb
<%= content.body %>

app/views/contents/_image.html.erb
<%= image_tag(image.source.url, size: "300x300") %>

app/views/contents/_pic.html.erb
<%= link_to pic_url(pic), data: { turbo_frame: "_top" } do %>
<%= tag.figure class:"picLoader", style: "--loading-url: url(#{pic.source.variant(:small).url}); view-transition-name: img_#{dom_id(pic)}", data:{controller:"pic"} do %>
    <%= image_tag(pic.source.variant(:medium), alt: pic.body, id: dom_id(pic), class: "imgloader",loading: "lazy", data:{pic_target: "pic", action:"load->pic#loaded"}) %>
    <%= tag.figcaption pic.body %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Site Gen" %></title>
    <meta name="view-transition" content="same-origin" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_links.html.erb
<% pages.each do |page| %>
    <li>
        <a href="#<%= page.anchor %>"><%= page.type %></a>
    </li>
<% end %>

app/views/pages/_gallery.html.erb
<section class="gallery" id="gallery">
    <h2><%= render gallery.get_content("title") %></h2>
    <%= tag.div class: "container", style:"view-transition-name: fade" do %>
        <%= render gallery.pics, size: "small" %>
    <% end %>
    <%= tag.div class: "browsePics" do %>
        <%= tag.button "right" %>
    <% end %>
</section>

app/views/pages/_hero.html.erb
<section class="hero">
    <h1><%= render hero.get_content("title") %></h1>
    <div class="logo-container"><%= render hero.get_content("logo") %></div>
    <p><%= render hero.get_content("tagline") %></p>
</section>

app/views/pages/_page.html.erb
<section id="<%= page.anchor %>">
    page <%= page.id %>
    # <%= render "_pages#{page.type}" %>
</section>

app/views/pages/_pages.html.erb
<%= render site.pages %>

app/views/pics/index.html.erb
<%= turbo_frame_tag dom_id(@gallery) do %>
    <%= tag.div class: "container" do %>
        <%= render @pics, size: "medium" %>
    <% end %>
<% end %>

app/views/pics/show.html.erb
<%= tag.div class: "bigPic" do %>
    <%= link_to "Back" ,site_url(@pic.page.site, anchor: "gallery") %>
        <%= tag.figure class:"picLoader", style: "--loading-url: url(#{@pic.source.variant(:medium).url}); view-transition-name: img_#{dom_id(@pic)}", data:{controller:"pic"} do %>
        <%= image_tag(@pic.source.variant(:big), alt: @pic.body, id: dom_id(@pic), class: "imgloader",loading: "lazy", data:{pic_target: "pic", action:"load->pic#loaded"}) %>
        <%= tag.figcaption @pic.body %>
    <% end %>
<% end %>

app/views/sites/_form.html.erb
<%= form_with(model: site) do |form| %>
  <% if site.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
        <% site.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/_site.html.erb
<div id="<%= dom_id site %>">
  <p>
    <strong>Title:</strong>
    <%= site.title %>
  </p>

</div>

app/views/sites/edit.html.erb
<% content_for :title, "Editing site" %>

<h1>Editing site</h1>

<%= render "form", site: @site %>

<br>

<div>
  <%= link_to "Show this site", @site %> |
  <%= link_to "Back to sites", sites_path %>
</div>

app/views/sites/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Sites" %>

<h1>Sites</h1>

<div id="sites">
  <% @sites.each do |site| %>
    <%= render site %>
    <p>
      <%= link_to "Show this site", site %>
    </p>
  <% end %>
</div>

<%= link_to "New site", new_site_path %>

app/views/sites/new.html.erb
<% content_for :title, "New site" %>

<h1>New site</h1>

<%= render "form", site: @site %>

<br>

<div>
  <%= link_to "Back to sites", sites_path %>
</div>

app/views/sites/show.html.erb
<nav>
  <ul>
    <%= render "links/links", pages: @site.pages %>
  </ul>
</nav>
<main>
  <%= render "pages/pages", site: @site %>
</main>